# Generated by Django 5.1.3 on 2024-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psc',
            name='lst_ent_cslt_ent_1',
        ),
        migrations.RemoveField(
            model_name='psc',
            name='lst_ent_cslt_ent_2',
        ),
        migrations.RemoveField(
            model_name='psc',
            name='lst_ent_cslt_ent_3',
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_1_mtt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Montant de l'offre de l'entreprise 1"),
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_1_ncc_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="NCC et nom de l'entreprise 1"),
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_2_mtt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Montant de l'offre de l'entreprise 2"),
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_2_ncc_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="NCC et nom de l'entreprise 2"),
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_3_mtt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Montant de l'offre de l'entreprise 3"),
        ),
        migrations.AddField(
            model_name='psc',
            name='lst_ent_cslt_ent_3_ncc_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="NCC et nom de l'entreprise 3"),
        ),
        migrations.AlterField(
            model_name='psc',
            name='lst_ent_cslt_nb_ent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de soumissionnaires'),
        ),
        migrations.AlterField(
            model_name='psc',
            name='lst_ent_cslt_ref_acc_pr_cslt_mn_cq_ent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Référence de l'accord pour consulter moins de cinq entreprises"),
        ),
        migrations.AlterField(
            model_name='psl',
            name='res_del_rec_evt_cst',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name='eConstat'),
        ),
        migrations.AlterField(
            model_name='psl',
            name='res_del_rec_evt_nb_rec',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de recours'),
        ),
        migrations.AlterField(
            model_name='psl',
            name='res_del_rec_evt_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
